//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPage
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CarsId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Fees { get; set; }
    
        public virtual CarsDetail CarsDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
